### ISSUE TITLE
Zsh Compatibility

### ISSUE THREAD

**Issue by 0xmachos** [0xmachos/mOSL#20]
macOS Catalina will replace `bash` with `zsh` as the [default shell](https://support.apple.com/en-us/HT208050).

**Comment by 0xmachos** [comment]
Executing `Lockdown` with `zsh` produces the following:
```
0xmachos@0xmachoss-Mac mOSL % zsh Lockdown
verify_signature:6: command not found: tr
follow_symlink:6: command not found: basename
follow_symlink:8: BASH_SOURCE[0]: parameter not set
```

The following functions will need to be reworked:

- [ ] [`verify_signature`](https://github.com/0xmachos/mOSL/blob/cc397501f71e47854753f4f708c3a5462321d5aa/Lockdown#L195-L229)
- [ ] [`follow_symlink`](https://github.com/0xmachos/mOSL/blob/cc397501f71e47854753f4f708c3a5462321d5aa/Lockdown#L165-L192)

**Comment by 0xmachos** [comment]
The following errors 
```
verify_signature:6: command not found: tr
follow_symlink:6: command not found: basename
```
have been resolved by 507f224d953a5e97f38f7291c7a826a8239b8aec. 

`verify_signature` does not need a rework. 

Hopefully the only thing left to do is find the Zsh equivalent of `BASH_SOURCE`.

**Comment by 0xmachos** [comment]
Testing with `/usr/bin/env zsh` produces the following error:
```
dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
  Referenced from: /usr/local/bin/zsh
  Reason: image not found
Abort trap: 6
```

Testing with `/bin/zsh` produces no errors.

Since Bash is still shipped with Catalina I'm not going to address this. Leaving the Lockdown shebang as `#!/usr/bin/env bash`.

**Comment by geoff-nixon** [comment]
`strings /bin/sh`
`whence env`

**Comment by geoff-nixon** [comment]
> Since Bash is still shipped with Catalina I'm not going to address this. Leaving the Lockdown shebang as `#!/usr/bin/env bash`.

A eulogy for this closed issue, a poem in Korn-y shell:

```
whence env
strings /bin/sh
# ln -s /bin/dash # or, the colonoscopy shebang:
echo ': # foo=$(osascript -e "display dialog \"shell > seychelles"\")' > /usr/local/bin/[[
chmod +x /usr/local/bin/[[ # whence $0ffshore profiteer"
```
