### ISSUE TITLE
eficheck doesn't work on T2 equipped Macs

### ISSUE THREAD

**Issue by 0xmachos** [0xmachos/mOSL#4]
## Problem
The `eficheck`utility does not work on [Macs equipped with the T2 chip](https://support.apple.com/en-us/HT208862). Currently:
- 2018 MacBook Pros
- iMac Pro

The following descibes testing on a 2018 MacBook Pro. 

The kext responsible for `eficheck`, `com.apple .driver.eficheck`, is not loaded however is present at `/System/Library/Extensions/eficheck.kext`. 

Attempting to run `eficheck` produces the following output:
```
$ /usr/libexec/firmwarecheckers/eficheck/eficheck --integrity-check
ReadBinaryFromKernel: No matching services found. Either this system is not supported by eficheck, or you need to re-load the kext
IntegrityCheck: couldn't get EFI contents from kext
```

Loading `eficheck.kext` and rerunning `eficheck` doesn't work and produces the same output as above. 

## Fix

Need to be able to identify, from bash, Macs which have a T2 chip and skip the `check_EFI_integrity` function.

**Comment by 0xmachos** [comment]
## Fix 

Using the `system_profiler` utility we can view details of the T2 aka `iBridge`. 

```
$ system_profiler SPiBridgeDataType
Controller:

    Controller Information:

      Model Name: Apple T2 chip
      Firmware Version: 15P6703
      Boot UUID: ***REDACTED***
```
Unfortunately running `system_profiler SPiBridgeDataType` on a system that does not have a T2 chip still returns true. 

We can use `grep` to check for the T2: 

```
if system_profiler SPiBridgeDataType | grep 'T2'; then 
  echo "T2 Present" 
else 
  echo "No T2 Present"
  check_EFI_integrity
fi
```

**Comment by 0xmachos** [comment]
Need to test if `eficheck` works on the 2016 and 2017 MacBook Pro with Touchbar models and what `system_profiler SPiBridgeDataType` returns.

**Comment by 0xmachos** [comment]
From a 2016 TouchBar MBP ([MacBookPro13,3](https://support.apple.com/kb/SP749?locale=en_US)):

```
$ system_profiler SPiBridgeDataType
Controller:

    Controller Information:

      Model Name: Apple T1 chip
      Firmware Version: 14Y664 
```

```
$ /usr/libexec/firmwarecheckers/eficheck/eficheck --integrity-check
EFI Version: MBP133.88Z.0247.B00.1806261159
Primary allowlist version match found. No changes detected in primary hashes. 
```

**Comment by 0xmachos** [comment]
490494c4c36d45fb68552177d2c381d4ab8461fb addresses this by checking if the Mac has a T2 chip via `system_profiler SPiBridgeDataType` and exiting `check_efi_integrity` if it does. 

Keeping this open to add more information.

**Comment by 0xmachos** [comment]
From a 2016 TouchBar MBP ([MacBookPro13,2](https://support.apple.com/kb/SP748?locale=en_US)):

```
$ system_profiler SPiBridgeDataType
iBridge:

    iBridge Information:

      Model Name: T1
      Model Identifier: iBridge1,1
      Build Version: 14Y664
      Serial Number: ***
      Hostname: localbridge
      Type: Internal
```

```
$ /usr/libexec/firmwarecheckers/eficheck/eficheck --integrity-check
EFI Version: MBP132.88Z.0244.B00.1804091703
Primary allowlist version match found. No changes detected in primary hashes.
```

**Comment by mikeorama** [comment]
From a 2017 TouchBar MBP ([MacBookPro14,3](https://support.apple.com/kb/SP756?locale=en_US)):

```
$ system_profiler SPiBridgeDataType
Controller:

     Controller Information:

     Model Name: Apple T1 chip
     Firmware Version: 14Y664
```

```
$ /usr/libexec/firmwarecheckers/eficheck/eficheck --integrity-check
EFI Version: MBP143.88Z.0178.B00.1806261159
Primary allowlist version match found. No changes detected in primary hashes.
```

**Comment by 0xmachos** [comment]
@mikeorama thank you!

**Comment by 0xmachos** [comment]
From a 2017 TouchBar MBP ([MacBookPro14,3](https://support.apple.com/kb/SP756?locale=en_US)):

Language: French
```
$ system_profiler SPiBridgeDataType
Controller:

    Informations sur le contrôleur:

      Model Name: Apple T1 puce
      Firmware Version: 14Y664
```

```
$ /usr/libexec/firmwarecheckers/eficheck/eficheck --integrity-check
EFI Version: MBP143.88Z.0178.B00.1806261159
Primary allowlist version match found. No changes detected in primary hashes.
```

[Source](https://twitter.com/ranvel/status/1024834278872567808)

**Comment by 0xmachos** [comment]
Filed a Radar. 

Here's the Open Radar entry: https://openradar.appspot.com/radar?id=5020911870672896

**Comment by 0xmachos** [comment]
Apple closed my Radar with the comment:

```
Regarding this: said “My request is that there should be some way to verify the integrity 
of EFI from userland on Macs with T2 chips.”  

The architecture for T2 systems is such that there is much less value in attempting to 
make eficheck work with it, and thus enhancements are not currently on our plans.
```

**Comment by 0xmachos** [comment]
mOSL will skip `check_efi_integrity` when running on a Mac with a T2 chip, this was added by 490494c4c36d45fb68552177d2c381d4ab8461fb. 

Given Apples response I don't think there's anything else that can be done. If this changes I'll reopen this issue.
