### ISSUE TITLE
Support bash 3.2.x

### ISSUE THREAD

**Issue by 0xmachos** [0xmachos/mOSL#6]
Requiring bash `4.x` per f1cc5157f19ffb38d4cd4d9e18b319201e59810b severely limits the usefulness of this script as `4.x` must be installed out of band (`brew`). Stock macOS ships with bash `3.2.57`.

We should work to remove the `4.x` dependancy so that `Lockdown` can be run on stock macOS installs.  

Reasons for requiring `4.x`:
- mapfile, introduced in `4.0` is required
- set -u will cause ‘items[@]: unbound variable’ on `3.2`

**Comment by 0xmachos** [comment]
From testing it looks like 061d1580342f5b5275ac88365ab4bf75559d3534 is the only change needed.

`set -u` will only result in `items[@]: unbound variable` if the array `items` is empty. This isn't an issue for Lockdown.

**Comment by stampycode** [comment]
Is this a Bash version related issue?

    $ ./Lockdown audit
    ./Lockdown: line 192: "18" - 1 : syntax error: operand expected (error token is ""18" - 1 ")

I'm running `Bash 3.2.57`

**Comment by 0xmachos** [comment]
Hi @stampycode, 

I can confirm this is a bash version issue. 

I'll push a fix for this tonight.

**Comment by 0xmachos** [comment]
@stampycode I've just released [v1.7.1](https://github.com/0xmachos/mOSL/releases/tag/v1.7.1) which should addressed this

**Comment by stampycode** [comment]
@0xmachos did you update the minisign checksum?

**Comment by 0xmachos** [comment]
@stampycode yes. Please don't use the code in `master` as it won't be verifiable. You can get the latest release which will be signed from: https://github.com/0xmachos/mOSL/releases/latest

**Comment by stampycode** [comment]
ah gotcha. I just did a `git pull`. mybad.

**Comment by stampycode** [comment]
Hey @0xmachos, please see new error below.

    $ ./Lockdown fix 3
    [⚠️ ] You are about to engage FIX mode which WILL make changes to your Mac 💻
    [⚠️ ] Do you want to continue? (y/N) y
    [✅] tim.stamp has chosen to continue
    Results:
      [❌] Require an administrator password to access system-wide preferences
    ./Lockdown: line 633: fix_fails: unbound variable

**Comment by 0xmachos** [comment]
@stampycode Ah, I've already [fixed that](https://github.com/0xmachos/mOSL/commit/9b68f51fdaad76818fde30c83f7b8d8882454ba2) but I've not published a release yet. 

Give me five minutes and I'll have `v1.8.0` for you.

**Comment by 0xmachos** [comment]
@stampycode [`v1.8.0`](
https://github.com/0xmachos/mOSL/releases/tag/v1.8.0) should address that error.

**Comment by 0xmachos** [comment]
@stampycode thanks for reporting these two bugs. If you find anything else please open a new issue. 

This appears to be resolved so I'm closing the issue.
